# Generated by Django 4.1.4 on 2022-12-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('decision', models.TextField(verbose_name='Решение')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
            ],
        ),
    ]
